apiVersion: v1
kind: Namespace
metadata:
  name: quobyte
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quobyte-deployer
  namespace: quobyte
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: quobyte-deployer
  namespace: quobyte
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
    resources:
      - configmaps
      - daemonsets
      - deployments
      - namespaces
      - nodes
      - pods
      - services
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: quobyte-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quobyte-deployer
subjects:
- kind: ServiceAccount
  name: quobyte-deployer
  namespace: quobyte
