apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: data
spec:
  template:
    metadata:
      labels:
        role: data
        version: VERSION
    spec:
      containers:
      - name: quobyte-metadata
        image: quay.io/quobyte/quobyte-server:VERSION
        securityContext:
          privileged: true
        env:
          - name: QUOBYTE_SERVICE
            value: data
          - name: QUOBYTE_REGISTRY
            value: registry
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MAX_MEM
            valueFrom:
              configMapKeyRef:
                name: quobyte-config
                key: data.max_mem
          - name: MIN_MEM
            valueFrom:
              configMapKeyRef:
                name: quobyte-config
                key: data.min_mem
        command:
          - /bin/bash
          - -xec
          - |
            sed "s/.*MIN_MEM_DATA=.*/MIN_MEM_DATA=${MIN_MEM}/" -i /etc/default/quobyte
            sed "s/.*MAX_MEM_DATA=.*/MAX_MEM_DATA=${MAX_MEM}/" -i /etc/default/quobyte
            if [ ! -f /devices/data/QUOBYTE_DEV_SETUP ]; then
              mkdir -p /devices/data
              cat >/devices/data/QUOBYTE_DEV_SETUP <<EOF
            device.serial=$(uuidgen)
            device.model=Kubernetes-hostDir
            device.type=DATA_DEVICE
            EOF
            fi
            exec /bin/bash -x /opt/main.sh
        volumeMounts:
          - name: devices
            mountPath: /devices/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
      nodeSelector:
        quobyte_data: "true"
      volumes:
      - name: devices
        hostPath:
          path: /mnt/data
