apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: data
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/prometheus'
        prometheus.io/port: '7873'
      labels:
        role: data
        version: VERSION
    spec:
      containers:
      - name: quobyte-metadata
        image: quay.io/quobyte/quobyte-server:VERSION
        securityContext:
          privileged: true
        env:
          - name: QUOBYTE_SERVICE
            value: data
          - name: QUOBYTE_REGISTRY
            value: _quobyte._tcp.registry
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        command:
          - /bin/bash
          - -xec
          - |
            hostname $NODENAME
            sed "s/.*MIN_MEM_DATA=.*/MIN_MEM_DATA=${MIN_MEM}/" -i /etc/default/quobyte
            sed "s/.*MAX_MEM_DATA=.*/MAX_MEM_DATA=${MAX_MEM}/" -i /etc/default/quobyte
            if [ ! -f /devices/data/QUOBYTE_DEV_SETUP ]; then
              mkdir -p /devices/data
              cat >/devices/data/QUOBYTE_DEV_SETUP <<EOF
            device.serial=$(uuidgen)
            device.model=Kubernetes-hostDir
            device.type=DATA_DEVICE
            EOF
            fi

            if [ ! -f /devices/data/UUID ]; then
              echo uuid=$(uuidgen) >> /devices/data/UUID
            fi

            cat /devices/data/UUID >> /etc/quobyte/$QUOBYTE_SERVICE.cfg

            exec /bin/bash -x /opt/main.sh
        volumeMounts:
          - name: devices
            mountPath: /devices/data
        ports:
          - name: rpc-tcp
            containerPort: 7873
            protocol: TCP
        readinessProbe:
          timeoutSeconds: 5
          httpGet:
            port: 7873
            path: /
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 5
          httpGet:
            port: 7873
            path: /
      nodeSelector:
        quobyte_data: "true"
      volumes:
      - name: devices
        hostPath:
          path: /mnt/data
