apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: metadata
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/prometheus'
        prometheus.io/port: '7872'
      labels:
        role: metadata
        version: VERSION
    spec:
      containers:
      - name: quobyte-metadata
        image: quay.io/quobyte/quobyte-server:VERSION
        securityContext:
          capabilities:
            add:
              - SYS_RESOURCE
        env:
          - name: QUOBYTE_SERVICE
            value: metadata
          - name: QUOBYTE_REGISTRY
            value: registry
        command:
          - /bin/bash
          - -xec
          - |
            sed "s/.*MIN_MEM_METADATA=.*/MIN_MEM_METADATA=${MIN_MEM}/" -i /etc/default/quobyte
            sed "s/.*MAX_MEM_METADATA=.*/MAX_MEM_METADATA=${MAX_MEM}/" -i /etc/default/quobyte
            if [ ! "$(ls -A /devices)" ] && [ ! -f /devices/QUOBYTE_DEV_SETUP ]; then
              mkdir -p /devices
              cat >/devices/QUOBYTE_DEV_SETUP <<EOF
            device.serial=$(uuidgen)
            device.model=Kubernetes-hostDir
            device.type=METADATA_DEVICE
            EOF
            fi

            if [ ! -f /devices/UUID ]; then
              echo uuid=$(uuidgen) >> /devices/UUID
            fi

            cat /devices/UUID >> /etc/quobyte/$QUOBYTE_SERVICE.cfg

            exec /bin/bash -x /opt/main.sh
        volumeMounts:
          - name: devices
            mountPath: /devices
        ports:
          - name: rpc-tcp
            containerPort: 7872
            protocol: TCP
        readinessProbe:
          timeoutSeconds: 5
          httpGet:
            port: 7872
            path: /
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 5
          httpGet:
            port: 7872
            path: /
      nodeSelector:
        quobyte_metadata: "true"
      volumes:
      - name: devices
        hostPath:
          path: /mnt/metadata
