apiVersion: v1
kind: Service
metadata:
  name: registry
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/prometheus'
    prometheus.io/port: '7871'
spec:
  clusterIP: "None" # headless service => kube-dns will return pod IPs
  ports:
    - name: quobyte # available as _quobyte._tcp.registry via DNS
      port: 7861
      protocol: TCP
    - name: rpc-udp
      port: 7861
      protocol: UDP
    - name: http
      port: 7871
      protocol: TCP
  selector:
    role: registry
