apiVersion: v1
kind: Service
metadata:
  name: webconsole
spec:
  ports:
    - name: web80
      targetPort: 8080
      port: 80
      protocol: TCP
    - name: web
      port: 8080
      protocol: TCP
  selector:
    role: webconsole
